export enum LeadSource {
  WEBSITE = 'WEBSITE',
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  REFERRAL = 'REFERRAL',
  WALK_IN = 'WALK_IN',
  NEWSPAPER = 'NEWSPAPER',
  TELE_CALL = 'TELE_CALL',
  WHATSAPP = 'WHATSAPP'
}